```bash
/bin/magento setup:install \
--base-url=http://coreops.l37sg0.com \ 
--db-host=mysql \
--db-name=magento \ 
--db-user=root \
--db-password=rootpassword \ 
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \ 
--admin-user=admin \
--admin-password=admin123 \ 
--language=bg_BG \
--currency=BGN \
--timezone=Europe/Sofia \ 
--use-rewrites=1 \
--search-engine=elasticsearch8 \ 
--elasticsearch-host=elasticsearch \ 
--elasticsearch-port=9200 \
--elasticsearch-index-prefix=coreops \
```
